spring:
  config:
    import: "optional:classpath:.properties"

app:
  application-name: tgBotService
  server:
    port: 8080
  logging:
    root-level: info
    bot-level: debug
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  telegram:
    name: Weather_Big_Bot
    token: ${TOKEN}

logging:
  level:
    org.springframework.boot.context.properties: TRACE
    org.springframework.boot.context.config: DEBUG

