spring:
  config:
    import: "optional:classpath:.properties"
  datasource:
    url: jdbc:postgresql://localhost:5432/weather_bot
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver

app:
  application-name: botService
  server:
    port: 8080
  logging:
    root-level: info
    bot-level: debug
  telegram:
    bot-name: Weather_Big_Bot
    token: ${TOKEN}

logging:
  level:
    org.springframework.boot.context.properties: TRACE
    org.springframework.boot.context.config: DEBUG

