server:
  port: 8080
  error:
    include-message: always

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  datasource:
    driver-class-name: org.postgresql.Driver

app:
  application-name: botService
  telegram:
    bot-name: Weather_Big_Bot
    token: ${TOKEN}
  rabbitmq:
    weather-queue: weatherRequestQueue
    user-queue: userUpdateQueue
    dlx: weather-exchange.dlx
    weather-key: weather-routing-key
    user-key: user-routing-key

grpc:
  client:
    userService:
      address: "localhost:9090"
      negotiationType: plaintext

logging:
  level:
    com.example.bot.configuration.MessageConverterConfig: DEBUG
    com.example.bot.configuration.GrpcUserServiceClientConfiguration: DEBUG
    org.springframework.web: DEBUG
    org.springframework.boot: INFO

---
spring:
  config:
    activate:
      on-profile: dev
    import: "optional:classpath:.properties"
  datasource:
    url: jdbc:postgresql://localhost:5432/weather_bot
    username: postgres
    password: pass

logging:
  level:
    org.springframework.boot.context.properties: TRACE
    org.springframework.boot.context.config: DEBUG

---
spring:
  config:
    activate:
      on-profile: prod
    import: "optional:classpath:.properties"
  datasource:
    url: jdbc:postgresql://db:5432/weather_bot
    username: postgres
    password: pass

logging:
  level:
    org.springframework.boot.context.properties: TRACE
    org.springframework.boot.context.config: DEBUG
    com.example.bot.telegram: DEBUG
    com.example.bot.clients: DEBUG
    org.springframework.web: DEBUG
    org.springframework.boot: INFO
