app:
  application-name: tgBotService
  server:
    port: ${BOT_PORT}
  logging:
    root-level: info
    bot-level: debug
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
  telegram:
    bot-name: "Weather_Big_Bot"
    token: ${TELEGRAM-TOKEN}
