server:
  port: 8081
  error:
    include-message: always
spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
grpc:
  server:
    port: 9090
app:
  rabbitmq:
    user-queue: userUpdateQueue
    dlx:  weather-exchange.dlx
    user-key: user-routing-key
logging:
  level:
    com.example.userservice.services.UserUpdateListener: DEBUG
---

spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    liquibase:
      change-log: classpath:db/changelog/db.changelog-master.xml

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/weather_bot
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://db:5432/weather_bot
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver

